#!/usr/bin/bash

gst-launch-1.0 udpsrc port=7002 ! application/x-rtp, encoding-name=H264,payload=96 ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! autovideosink &
gst-launch-1.0 udpsrc port=7003 ! application/x-rtp, encoding-name=H264,payload=96 ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! autovideosink
