name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository.
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_U }}
        password: ${{ secrets.DOCKERHUB_P }}

    - name: Build and push ares-stream
      uses: docker/build-push-action@v6
      with:
        context: ./ares-streaming/.
        push: true
        tags: ozurover/ares-streaming:latest

    - name: Build and push ares-teleops
      uses: docker/build-push-action@v6
      with:
        context: ./ares-teleops/.
        push: true
        tags: ozurover/ares-teleops:latest
